archetypeDir           = "archetypes"
author                 = "Akshit Dhar"
baseUrl                = "https://goakshit.github.io/"
buildDrafts            = false
relativeURLs           = true
canonifyUrls           = true
contentDir             = "content"
languageCode           = "en-us"
layoutDir              = "layouts"
publishDir             = "public"
theme                  = "pixyll"
themesDir              = "themes"
title                  = "Akshit Dhar"
enableEmoji            = true
DefaultContentLanguage = "en"

[Languages]
[Languages.en]
weight = 1


[indexes]
  category = "categories"
  tag = "tags"

[params]
  mainSections = ["post"]
  twitter_username = "dharakshit"
  paginate = 5