[module]
  [[module.imports]]
    path = "github.com/monkeyWzr/hugo-theme-cactus"
    disable=false

[params]
  postsOnHomePage = 1000
  colortheme = "white" # dark, light, white, or classic
  description = "Software Engineer | Go | Microservices | Docker | Kubernetes | Avid Reader"
  mainSection = "/"
  mainSectionTitle = "Blog"
  BaseURL = "https://goakshit.github.io/"
  logo = "https://golang.org/doc/gopher/favicon.svg"
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

[[params.social]]
  name = "github"
  link = "https://github.com/goakshit"

[[params.social]]
  name = "email"
  link = "akshitdhar@live.com"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/dharakshit/"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Thoughts"
url = "/thoughts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

buildDrafts            = true
relativeURLs           = true
canonifyUrls           = true
contentDir             = "content"
languageCode           = "en-us"
publishDir             = "public"
theme                  = ["hugo-theme-cactus"]
DefaultContentLanguage = "en"
googleAnalytics = "G-EEQS586TBX"

# Post page settings
show_updated = true # default
showReadTime = true # default